title: isecut1ty
author: ibr2
email: enusec@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Github Pages by: SCOT

# social links
twitter_username: _enusec_
github_username:  ENUSEC

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker
